apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy
  namespace: openshift-gitops
spec:
  destination:
    name: local-cluster
  project: default
  source:
    path: policies
    repoURL: https://github.com/michaelkotelnikov/policy-demo
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
