apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mariadb
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: 'mariadb'
    name: '*'
    server: '*'
  sourceRepos:
  - '*'
